apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-agent-sa
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: docker
      image: docker:20.10.8
      command: ["sleep", "1d"]
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock # We use the k8s host docker engine
      env:
        - name: HTTP_PROXY
          value: http://10.0.7.94:8080
        - name: HTTPS_PROXY
          value: http://10.0.7.94:8080
  imagePullSecrets:
    - name: nexusregistrycreds
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
