#Get these from  https://gitlab.pontsystems.eu/klucsikkrisztian/jenkins-agent-templates
apiVersion: v1
kind: Pod
metadata:
  name: test

spec:
  nodeSelector:
    kubernetes.io/hostname: klucsik-bazooka
  containers:  # list of containers that you want present for your build, you can define a default container in the Jenkinsfile
    - name: docker
      image: docker:20.10.8
      command: ["sleep", "1d"]
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock # We use the k8s host docker engine
  imagePullSecrets:
    - name: nexusregistrycreds
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock
